server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.175.129:3306/xc-content?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.xuecheng: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/content-service"

knife4j:
  enable: true
  openapi:
    title: "学成在线内容管理系统"
    description: "内容系统管理系统对课程相关信息进行管理"
    email: ruyi_wei@hnu.edu.cn
    concat: ruyi
    url: https://weiruyi.github.io/
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.xuecheng.content.api

