### 申请验证码
POST {{checkcode_host}}/checkcode/pic

### 手机验证码
POST {{checkcode_host}}/checkcode/phone?param1=17786279251

### 校验验证码
POST {{checkcode_host}}/checkcode/verify?key=checkcode:e0eb055f2d114309a1b8afb39f63cab9&code=AQN5