###
POST http://{{content_host}}/content/course/list
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "java",
  "publishStatus": ""
}


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "123",
  "teachmode": "200002",
  "users": "1",
  "tags": "",
  "grade": "204001",
  "description": ""
}


### 查询课程
GET {{gateway_host}}/content/course/93

###
GET {{gateway_host}}/content/teachplan/74/tree-nodes

###授权码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=8R119O&redirect_uri=http://www.51xuecheng.cn

###密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123

### 校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MjIzMjIzODgsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6IjdiMDcyMjYyLTMzMDItNDNjZi1hMzE2LTlhYTkxY2YxYTEyZSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.HWhB8de3udZU_r8kIKdHOaQo4_JaPpZN7KcO2tfj5Fg
