###
POST http://{{content_host}}/content/course/list
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "java",
  "publishStatus": ""
}

###课程查询
GET {{gateway_host}}/content/course/40

###课程查询
GET {{gateway_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcyMjMzMzMwOSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI4ZjA1NDQ4My1kNThlLTRmYTQtYmMyZi01YzM5MmYxMGU0NzMiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.rHJkN1itAoPb3oAukFoF2gsdZdh5l-cnNS_D4B1WFjo

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "123",
  "teachmode": "200002",
  "users": "1",
  "tags": "",
  "grade": "204001",
  "description": ""
}


### 查询课程
GET {{gateway_host}}/content/course/93

###
GET {{gateway_host}}/content/teachplan/74/tree-nodes

###授权码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=8R119O&redirect_uri=http://www.51xuecheng.cn

###密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=t1&password=111111

### 校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQxXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcyMjMzMzMwOSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI4ZjA1NDQ4My1kNThlLTRmYTQtYmMyZi01YzM5MmYxMGU0NzMiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.rHJkN1itAoPb3oAukFoF2gsdZdh5l-cnNS_D4B1WFjo

################扩展认证请求参数后######################
###密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"t1","authType":"password","password":"111111"}